### ISSUE TITLE
Add visitor counter and github stats

### ISSUE THREAD

**Issue by sanchitvj** [Rishit-dagli/Rishit-dagli#3]
Code for GitHub stats:  
`![](https://github-readme-stats.vercel.app/api?username=id&show_icons=true&title_color=E88795&icon_color=FF33FF&text_color=D6BCD5&bg_color=151515)`  
Replace id with your username.  

Code for visitor count:  
`![VisitorCount](https://profile-counter.glitch.me/{id}/count.svg)`

**Comment by Rishit-dagli** [comment]
@sanchitvj I already know about these APIs, this was in fact a part of my README some time ago, but to make the README as concise as possible I had to remove the GitHub stats. I hope that solved this, I am closing this issue as of now, let me know if I missed something.
