### ISSUE TITLE
Make the Banner Image more Readable

### ISSUE THREAD

**Issue by Prince-Shaikh** [Rishit-dagli/Rishit-dagli#5]
Hey, the banner image is really hard to read, can you change the light green box colors to something else or maybe try changing the other white boxes to black?

how about using Github's contributions chart's color shades, they will make it feel like the image is part of the page as a whole.

**Comment by Rishit-dagli** [comment]
Hi @Prince-Shaikh ,
Thanks a lot for pointing this out, I think the text becomes a bit unreadable in dark mode. I am already using the light mode color theme of the GitHub contributions chart. I think a great idea might be to have the text all in dark green shades to make it more readable.

**Comment by Prince-Shaikh** [comment]
Yup the dark green of activity boxes should look good 🙂

**Comment by Rishit-dagli** [comment]
Hi,
Thanks again for raising this issue I made the edit, and now this is fixed via commit [`20e225a`](https://github.com/Rishit-dagli/Rishit-dagli/commit/20e225ad6bf1fd9e10e48b02bf36a74bcef98161).

TL: DR here is the updated image now seems to be fixed to display properly on dark mode:
![image](https://user-images.githubusercontent.com/39672672/116784339-61b33580-aab1-11eb-952b-c37b9cd94ab4.png)

**Comment by Prince-Shaikh** [comment]
Looks better 👍🙂
