### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by hack-parthsharma** [Rishit-dagli/Rishit-dagli#8]
Can you please explain how you've created that awesome header in your readme ? Btw You're Readme is very cool !

**Comment by Rishit-dagli** [comment]
Thank You and feel free to take a look at [`custom-contributions`](https://github.com/Rishit-dagli/Rishit-dagli/tree/master/custom-contributions) directory which helps me do this.

**Comment by Rishit-dagli** [comment]
Feel free to reopen the issue for any more questions, at the moment I will close this issue
